### ISSUE TITLE
Export printSeparator

### ISSUE THREAD

**Issue by trev-dev** [PMunch/nancy#1]
Would it be possible to export the `printSeparator` template so that I don't have to copy it from the source code for my custom table formatter?

**Comment by PMunch** [comment]
Of course! Would you be able to make a PR for it? Otherwise it'll have to wait until I'm by a computer

**Comment by trev-dev** [comment]
Happily! Also, the custom table formatter in question adds arbitrary separators between rows.  This allows for "grouped" or nested rows.  It's a bit of a hack but if I can clean it up, would you like that PR too?

**Comment by trev-dev** [comment]
Seems to be working, thanks.
Ref: https://github.com/PMunch/nancy/pull/2
