### ISSUE TITLE
Example of use in README

### ISSUE THREAD

**Issue by shablipapu** [PMunch/nancy#3]
Hi this looks like a great program and exactly what I need. :) it would be easier for new users to get to grips with it if an example was included in the README!

Thanks!

**Comment by PMunch** [comment]
Happy to hear that the project could be helpful to someone else! There is a short snippet at the end of the source file: https://github.com/PMunch/nancy/blob/caabc8c44670c4d7208892af2bddbb4b0e569ce7/src/nancy.nim#L228-L258 which is what generates the output seen in the example image. But I guess that should be added to the README as well
